[mgr]
cwd = { fg = "cyan", bold = true }

# Find
find_keyword = { fg = "yellow", italic = true }
find_position = { fg = "red", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "cyan", bg = "cyan" }
marker_copied = { fg = "green", bg = "green" }
marker_cut = { fg = "red", bg = "red" }

# Border
border_symbol = "│"
border_style = { fg = "darkgray" }

# Highlighting
syntect_theme = "~/.config/current-theme/yazi.tmTheme"


[tabs]
active = { fg = "white", bg = "black" }
inactive = { fg = "white", bg = "darkgray" }


# Indicator of hovered file
[indicator]
parent  = { fg = "gray", bg = "darkgray" }
current = { fg = "black", bg = "cyan", bold = true }
preview = { fg = "yellow", underline = true }
padding = { open = "▐", close = "▌" }


[mode]
normal_main = { fg = "black", bg = "cyan", bold = true }
normal_alt  = { fg = "cyan", bg = "darkgray" }

# Select mode
select_main = { fg = "black", bg = "magenta", bold = true }
select_alt  = { fg = "magenta", bg = "darkgray" }

# Unset mode
unset_main = { fg = "black", bg = "red", bold = true }
unset_alt  = { fg = "red", bg = "darkgray" }


[status]
overall   = { bg = "reset" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "cyan" }
perm_read  = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "blue" }

# Progress
progress_label = { fg = "white", bold = true }
progress_normal = { fg = "white", bg = "darkgray" }
progress_error = { fg = "red", bg = "darkgray" }


[input]
border = { fg = "blue" }
title = {}
value = {}
selected = { reversed = true }


[pick]
border = { fg = "blue" }
active = { fg = "red" }
inactive = {}


[tasks]
border = { fg = "blue" }
title = {}
hovered = { underline = true }


[which]
mask = { bg = "black" }
cand = { fg = "cyan" }
rest = { fg = "gray" }
desc = { fg = "red" }
separator = "  "
separator_style = { fg = "darkgray" }


[help]
on = { fg = "red" }
run = { fg = "cyan" }
desc = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer = { fg = "black", bg = "white" }


# File-specific styles
[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "cyan" },

    # Videos
    { mime = "video/*", fg = "yellow" },
    { mime = "audio/*", fg = "yellow" },

    # Archives
    { mime = "application/zip", fg = "red" },
    { mime = "application/gzip", fg = "red" },
    { mime = "application/x-tar", fg = "red" },
    { mime = "application/x-bzip", fg = "red" },
    { mime = "application/x-bzip2", fg = "red" },
    { mime = "application/x-7z-compressed", fg = "red" },
    { mime = "application/x-rar", fg = "red" },

    # Fallback
    { url = "*", fg = "white" },
    { url = "*/", fg = "cyan", bold = true },
]
