gui:
  theme:
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - yellow
      - bold
    optionsTextColor:
      - cyan
    selectedLineBgColor:
      - blue
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - magenta
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
  nerdFontsVersion: "3"
  showRandomTip: false
  showCommandLog: false
  showBottomLine: true
  showPanelJumps: false
  border: rounded
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --line-numbers
